name: "test1"

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
            - revision: 281885
              runs-on: macos-14
            - revision: 281887
              runs-on: macos-14
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - run: |
        node server.js &
        REVISION="${{ matrix.revision }}"
        curl --fail https://s3-us-west-2.amazonaws.com/minified-archives.webkit.org/mac-ventura-x86_64%20arm64-release/$REVISION@main.zip -o $REVISION.zip
        mkdir browser
        cd browser
        unzip ../$REVISION.zip
        cd ..
        # sudo xattr -cr Release # This is needed to run the MiniBrowser on normal macOS 
        ./browser/Release/MiniBrowser.app/Contents/MacOS/MiniBrowser --url http://localhost:3001 &
        sleep 10
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.runs-on }}-with-${{ matrix.revision }}
        path: received.png
